### ISSUE TITLE
Material for MkDocs 사용

### ISSUE THREAD

**Issue by lill74** [phg98/hacktoberfestkorea#5]
안녕하세요, 올해도 hacktoberfest를 진행한다는 소식을 듣고 후다닥 달려오다가 어느 블로그에서 hacktoberfestkorea를 홍보하는 글을 보고 찾아오게 되었습니다!

**문제점**
제가 생각하기에는 단순히 markdown 을 이용하는 프로젝트는 관리도 어렵고, 사용이 불편할것 같습니다

**제안점**
Material for MkDocs를 사용해서 github page를 배포하는건 어떨까요? 이런 종류의 static site generator는 많이 있지만 사용자의 폭이 넓고, UI가 깔끔한 mkdocs를 사용하는게 좋을것 같습니다.

**Comment by lill74** [comment]
예시로 한번 만들어 봤습니다.
[https://lill74.github.io/hacktoberfestkorea/](https://lill74.github.io/hacktoberfestkorea/)

제가 포크해간 Repository입니다
[https://github.com/lill74/hacktoberfestkorea](https://github.com/lill74/hacktoberfestkorea)

**Comment by phg98** [comment]
우왓 감사감사합니다.
만들기는했어도 누가 봐주려나 했는데 첫번째로 관심주신 분입니다. 압도적 감사 드립니다 ㅠㅠ
지금 회사여서 퇴근후에 보겠습니다.
감사합니다

**Comment by lill74** [comment]
아닙니다 ㅋㅊㅋㅋㅋㅋ 재미있을것같아요!

**Comment by phg98** [comment]
엄청 깔끔하네요. 천지차이네요. 감동감동입니다 ㅠㅠ
  * 일단 너무 깔끔해서 아주 좋으데다가 추가로
  * 아주아주 초보자들이 간단하게 기여하기에 좋을것 같네요.  
마크다운 파일에 한 줄만 추가하는 형식으로요.

PR보내주시면 감사히 받겠습니다.

그런데 혹시 향후에 더 기능을 넣으려고 할때 제약이 되지 않을지...
그런 부분이 있을까요?

**Comment by lill74** [comment]
기본적인 HTML도 넣을수 있고, 혹시 원한다면 직접 static page를 수정해서 배포할수 있습니다! PR 보내겠습니다

**Comment by lill74** [comment]
Pull Request #6 에 추가해놨습니다!

**Comment by phg98** [comment]
아앗 머지 하고 나서 사이트 접속하니 readme파일 내용만 보입니다.
http://www.hacktoberfestkorea.com/
![image](https://user-images.githubusercontent.com/12092302/94591647-4b4abe80-02c3-11eb-8dc4-d0573dd01a1b.png)
뭐가 잘못된걸까요? ㅠㅠ

**Comment by phg98** [comment]
아하! setting에서 deploy branch를 gh-pages로 바꿔야 하는군요! 이제 잘 되는것 같습니다 ㅠㅠ

**Comment by phg98** [comment]
그런데 매뉴얼에 보니 이런 내용이 있는데 CNAME 파일을 docs 폴더로 옮겨야 하는 걸까요?
https://www.mkdocs.org/user-guide/deploying-your-docs/#custom-domains

Custom Domains
GitHub Pages includes support for using a Custom Domain for your site. In addition to the steps documented by GitHub, you need to take one additional step so that MkDocs will work with your custom domain. You need to add a CNAME file to the root of your docs_dir. The file must contain a single bare domain or subdomain on a single line (see MkDocs' own CNAME file as an example). You may create the file manually, or use GitHub's web interface to set up the custom domain (under Settings / Custom Domain). If you use the web interface, GitHub will create the CNAME file for you and save it to the root of your "pages" branch. So that the file does not get removed the next time you deploy, you need to copy the file to your docs_dir. With the file properly included in your docs_dir, MkDocs will include the file in your built site and push it to your "pages" branch each time you run the gh-deploy command.

**Comment by lill74** [comment]
아뇨 [여기](https://squidfunk.github.io/mkdocs-material/publishing-your-site/)에 있는 with GitHub Actions 보고 따라하시고, GitHub Pages 브랜치를 gh-pages오 바꿔주시면 됩니다!

**Comment by phg98** [comment]
그런데 lill74님이 그룹멤버 이*울님 맞으시죠? id만으로 매칭이 잘 안돼서.. ^^
한가지 부탁드릴것이 있는데, 다른 사람들이 이 저장소 포크받아서 로컬머신에서 돌릴때 어떻게 빌드 및 실행해야 하는지 설명이 필요할 것 같아요. 설치할 것들도 좀 있는것 같던데, 간단하게 빌드방법(로컬에서와 git-hub page에서)을 readme 또는 별도 파일로 작성해 주시면 좋겠습니다. 제가 별도 이슈로 등록해 두겠습니다.

**Comment by phg98** [comment]
아, 내용 변경되어서 새로 빌드하면 도메인 설정이 지워지네요.
위에 쓴 것 처럼 CNAME파일을 docs폴더로 복사하니 해결되었습니다. ^^
